#ifndef UNREALSDK_FEATURE_DEFINES_H
#define UNREALSDK_FEATURE_DEFINES_H

#if UNREALSDK_FLAVOUR == UNREALSDK_FLAVOUR_WILLOW
#define UNREALSDK_FEAT_OPTIONAL_FUNCTION_PARAMETERS
#define UNREALSDK_FEAT_EMULATED_WEAK_POINTER

#elif UNREALSDK_FLAVOUR == UNREALSDK_FLAVOUR_WILLOW64
#define UNREALSDK_FEAT_VIRTUAL_POINTER_ALIGNMENT 4
#define UNREALSDK_FEAT_OPTIONAL_FUNCTION_PARAMETERS
#define UNREALSDK_FEAT_EMULATED_WEAK_POINTER

#elif UNREALSDK_FLAVOUR == UNREALSDK_FLAVOUR_OAK
// empty for now
#else
#error "current unrealsdk flavour is unknown"
#endif

#endif
